# Generated by Django 3.0.7 on 2020-06-18 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
                ('is_mvp', models.BooleanField()),
                ('hire_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
