bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '100000':'$100,000',
  '200000':'$200,000',
  '300000':'$300,000',
  '400000':'$400,000',
  '500000':'$500,000',
  '600000':'$600,000',
  '700000':'$700,000',
  '800000':'$800,000',
  '900000':'$900,000',
  '1000000':'$1M+',
}

state_choices = {
        'Andaman & Nicobar Islands': 'Andaman & Nicobar Islands',
        'Andhra Pradhesh': 'Andhra Pradhesh',
        'Arunachal Pradhesh': 'Arunachal Pradhesh',
        'Assam': 'Assam',
        'Bihar': 'Bihar',
        'Chattisgarh': 'Chattisgarh',
        'Dadra & Nagar Haveli': 'Dadra & Nagar Haveli',
        'Daman & Diu': 'Daman & Diu',
        'Delhi': 'Delhi',
        'Goa': 'Goa',
        'Gujarat': 'Gujarat',
        'Harayana': 'Harayana',
        'Himachal Pradhesh': 'Himachal Pradhesh',
        'Jammu & Kashmir': 'Jammu & Kashmir',
        'Jharkhand': 'Jharkhand',
        'Karnataka': 'Karnataka',
        'Kerala': 'Kerala',
        'Lakshdhweep': 'Lakshadweep',
        'Madhya Pradhesh': 'Madhya Pradhesh',
        'Maharashtra': 'Maharashtra',
        'Manipur': 'Manipur',
        'Meghalaya': 'Meghalaya',
        'Mizoram': 'Mizoram',
        'Nagaland': 'Nagaland',
        'Odisha': 'Odisha',
        'Puducherry': 'Puducherry',
        'Punjab': 'Punjab',
        'Rajasthan': 'Rajasthan',
        'Sikkim': 'Sikkim',
        'Tamil Nadu': 'Tamil Nadu',
        'Telangana': 'Telengana',
        'Tripura': 'Tripura',
        'Uttar Pradhesh': 'Uttar Pradesh',
        'Uttrakhand': 'Uttrakhand',
        'West Bengal': 'West Bengal'
}

